services:
  postgres:
    image: postgres
    container_name: bs-business-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bugstalker
      POSTGRES_USER: bugstalker-user
      POSTGRES_PASSWORD: 12345678

  redis:
    image: redis
    container_name: bs-business-cache
    ports:
      - "6379:6379"

  spring-app:
    image: bs-business:1.0.0-SNAPSHOT
    container_name: bs-business-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev-local,swagger
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bugstalker
      SPRING_DATASOURCE_USERNAME: bugstalker-user
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - postgres
      - redis