services:
  postgres:
    image: postgres
    container_name: bs-business-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bugstalker
      POSTGRES_USER: bugstalker-user
      POSTGRES_PASSWORD: 12345678

  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"